"""update userdata user_id colun to nullable=False and fixed issue related to deleting user by adding  passive_deletes=True in relatioships

Revision ID: 21f8aa493a10
Revises: 246b6dc611ef
Create Date: 2024-09-20 13:14:30.324236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f8aa493a10'
down_revision: Union[str, None] = '246b6dc611ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_data', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_data', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
