"""Update models to have unifrom name of colum filepath (rather then file_path)

Revision ID: 246b6dc611ef
Revises: 84c6537bffbd
Create Date: 2024-09-20 03:18:14.546570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246b6dc611ef'
down_revision: Union[str, None] = '84c6537bffbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_report_templates', sa.Column('filepath', sa.String(length=255), nullable=True))
    op.drop_column('admin_report_templates', 'file_path')
    op.drop_column('contents', 'file_path')
    op.add_column('references', sa.Column('filepath', sa.String(length=255), nullable=True))
    op.drop_column('references', 'file_path')
    op.add_column('user_content_states', sa.Column('modified_filepath', sa.String(length=255), nullable=True))
    op.drop_column('user_content_states', 'modified_file_path')
    op.alter_column('user_data', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user_report_templates', sa.Column('filepath', sa.String(length=255), nullable=True))
    op.drop_column('user_report_templates', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_report_templates', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user_report_templates', 'filepath')
    op.alter_column('user_data', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user_content_states', sa.Column('modified_file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user_content_states', 'modified_filepath')
    op.add_column('references', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('references', 'filepath')
    op.add_column('contents', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_report_templates', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('admin_report_templates', 'filepath')
    # ### end Alembic commands ###
