"""update userdata user_id colun to nullable=False and fixed issue related to deleting user by adding  passive_deletes=Tr


Revision ID: 50b9aeb4c0cd
Revises: 21f8aa493a10
Create Date: 2024-09-20 13:18:43.787840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b9aeb4c0cd'
down_revision: Union[str, None] = '21f8aa493a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_feedbacks_content_id_fkey', 'user_feedbacks', type_='foreignkey')
    op.drop_constraint('user_feedbacks_user_id_fkey', 'user_feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'user_feedbacks', 'contents', ['content_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(None, 'user_feedbacks', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'user_feedbacks', type_='foreignkey')
    op.create_foreign_key('user_feedbacks_user_id_fkey', 'user_feedbacks', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('user_feedbacks_content_id_fkey', 'user_feedbacks', 'contents', ['content_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
