"""Updated models to ensure that uneccesary fields are set to nonw

Revision ID: 69e6234b6ba0
Revises: a9a08811426c
Create Date: 2024-09-20 01:04:14.592185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e6234b6ba0'
down_revision: Union[str, None] = 'a9a08811426c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
