"""Updated cotent model to provide default content 

Revision ID: 84c6537bffbd
Revises: 69e6234b6ba0
Create Date: 2024-09-20 03:01:58.174819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c6537bffbd'
down_revision: Union[str, None] = '69e6234b6ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('references', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_data', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_data', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_feedbacks', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_feedbacks', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_data', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_data', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('references', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
