"""Updted models to ensure relevant fields are set to nullable=True

Revision ID: a9a08811426c
Revises: 8dafcbe1a418
Create Date: 2024-09-20 00:46:04.888932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9a08811426c'
down_revision: Union[str, None] = '8dafcbe1a418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_report_templates', 'template_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('admin_report_templates', 'body_part',
               existing_type=postgresql.ENUM('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'),
               nullable=True)
    op.alter_column('admin_report_templates', 'modality',
               existing_type=postgresql.ENUM('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'),
               nullable=True)
    op.alter_column('admin_report_templates', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_profiles', 'report_templates')
    op.alter_column('user_report_templates', 'body_part',
               existing_type=postgresql.ENUM('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'),
               nullable=True)
    op.alter_column('user_report_templates', 'modality',
               existing_type=postgresql.ENUM('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'),
               nullable=True)
    op.alter_column('user_report_templates', 'template_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_report_templates', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_report_templates', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_report_templates', 'template_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_report_templates', 'modality',
               existing_type=postgresql.ENUM('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'),
               nullable=False)
    op.alter_column('user_report_templates', 'body_part',
               existing_type=postgresql.ENUM('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'),
               nullable=False)
    op.add_column('user_profiles', sa.Column('report_templates', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('admin_report_templates', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('admin_report_templates', 'modality',
               existing_type=postgresql.ENUM('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'),
               nullable=False)
    op.alter_column('admin_report_templates', 'body_part',
               existing_type=postgresql.ENUM('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'),
               nullable=False)
    op.alter_column('admin_report_templates', 'template_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
