"""Update UserData model to ensure that it has current_login , login_count and session_start_time fields

Revision ID: ac6c57e350d4
Revises: c008b7d7d233
Create Date: 2024-09-22 07:10:57.893650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6c57e350d4'
down_revision: Union[str, None] = 'c008b7d7d233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('current_login', sa.DateTime(), nullable=True))
    op.add_column('user_data', sa.Column('session_start_time', sa.DateTime(), nullable=True))
    op.add_column('user_data', sa.Column('login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'login_count')
    op.drop_column('user_data', 'session_start_time')
    op.drop_column('user_data', 'current_login')
    # ### end Alembic commands ###
