"""New base revision

Revision ID: bca081be0644
Revises: c008b7d7d233
Create Date: 2024-09-22 12:19:10.121452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bca081be0644'
down_revision: Union[str, None] = 'c008b7d7d233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'session_start_time')
    op.drop_column('user_data', 'login_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('login_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_data', sa.Column('session_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
