"""Fix foreign key in UserData

Revision ID: bff321451f8f
Revises: f8648235d3f5
Create Date: 2024-09-19 23:01:32.305986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff321451f8f'
down_revision: Union[str, None] = 'f8648235d3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_content_states', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('user_content_states', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'user_content_states', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('user_data', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_data', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('user_feedbacks', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_feedbacks', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('user_profiles', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint('user_profiles_content_id_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('user_profiles', 'content_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key('user_profiles_content_id_fkey', 'user_profiles', 'contents', ['content_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('user_profiles', 'user_id')
    op.drop_constraint(None, 'user_feedbacks', type_='foreignkey')
    op.drop_column('user_feedbacks', 'user_id')
    op.drop_constraint(None, 'user_data', type_='foreignkey')
    op.drop_column('user_data', 'user_id')
    op.drop_constraint(None, 'user_content_states', type_='foreignkey')
    op.alter_column('user_content_states', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_content_states', 'user_id')
    # ### end Alembic commands ###
