"""herolu dpeloyment next

Revision ID: fe0607b2c90d
Revises: bca081be0644
Create Date: 2024-09-22 12:22:19.408160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0607b2c90d'
down_revision: Union[str, None] = 'bca081be0644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('login_count', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'login_count')
    # ### end Alembic commands ###
