"""Add CPDActivityType and CPDLog models

Revision ID: 15bd403890b9
Revises: dc512aaabb73
Create Date: 2025-06-20 00:17:52.028089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bd403890b9'
down_revision: Union[str, None] = 'dc512aaabb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpd_activity_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('default_credits', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cpd_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('cpd_year_start', sa.String(length=10), nullable=False),
    sa.Column('cpd_year_end', sa.String(length=10), nullable=False),
    sa.Column('appraisal_cycle_start', sa.String(length=10), nullable=False),
    sa.Column('appraisal_cycle_end', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('has_reflection', sa.Boolean(), nullable=True),
    sa.Column('cpd_points_guideline', sa.String(length=50), nullable=True),
    sa.Column('cpd_points_claimed', sa.Float(), nullable=True),
    sa.Column('certificate_filename', sa.String(length=255), nullable=True),
    sa.Column('certificate_filepath', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['cpd_activity_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpd_logs')
    op.drop_table('cpd_activity_types')
    # ### end Alembic commands ###
