"""trying file and filepath fields

Revision ID: 15f0e62a1f85
Revises: b30e33aff5a6
Create Date: 2024-09-03 02:29:27.493231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f0e62a1f85'
down_revision = 'b30e33aff5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_contents_file'), ['file'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_file'))
        batch_op.drop_column('file')

    # ### end Alembic commands ###
