"""initial schema

Revision ID: 171a3ea716d2
Revises: 
Create Date: 2025-11-15 00:02:53.077842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '171a3ea716d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('TNM', 'RADS', 'TRAUMA', 'SCORING', 'OTHER', name='classification_category_enum'), nullable=False),
    sa.Column('modality', sa.Enum('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'), nullable=True),
    sa.Column('body_part', sa.Enum('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_systems_body_part'), 'classification_systems', ['body_part'], unique=False)
    op.create_index(op.f('ix_classification_systems_category'), 'classification_systems', ['category'], unique=False)
    op.create_index(op.f('ix_classification_systems_modality'), 'classification_systems', ['modality'], unique=False)
    op.create_index(op.f('ix_classification_systems_name'), 'classification_systems', ['name'], unique=True)
    op.create_index(op.f('ix_classification_systems_short_code'), 'classification_systems', ['short_code'], unique=False)
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=565), nullable=False),
    sa.Column('category', sa.Enum('GUIDELINES', 'CLASSIFICATIONS', 'DIFFERENTIAL_DIAGNOSIS', 'VETTING_TOOLS', 'ANATOMY', 'CURATED_CONTENTS', 'REPORT_CHECKER', 'RAD_CALCULATORS', 'TNM_STAGING', 'IMAGE_SEARCH', 'PHYSICS', 'GOVERNANCE_AUDITS', 'COURSES', 'RESEARCH_TOOLS', 'MUSIC', 'REPORT_TEMPLATE', name='category_name'), nullable=False),
    sa.Column('module', sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='status'), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=2083), nullable=True),
    sa.Column('embed_code', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('content_tags', sa.Text(), nullable=True),
    sa.Column('importance_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='importance_level'), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('paid_access', sa.Boolean(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=2083), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('view_duration', sa.Integer(), nullable=True),
    sa.Column('usage_statistics', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('estimated_reading_time', sa.Integer(), nullable=True),
    sa.Column('bookmark_count', sa.Integer(), nullable=True),
    sa.Column('related_content', sa.Text(), nullable=True),
    sa.Column('related_api_links', sa.Text(), nullable=True),
    sa.Column('accessibility_features', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_category'), 'contents', ['category'], unique=False)
    op.create_index(op.f('ix_contents_content_tags'), 'contents', ['content_tags'], unique=False)
    op.create_index(op.f('ix_contents_file'), 'contents', ['file'], unique=False)
    op.create_index(op.f('ix_contents_filepath'), 'contents', ['filepath'], unique=False)
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_keywords'), 'contents', ['keywords'], unique=False)
    op.create_index(op.f('ix_contents_module'), 'contents', ['module'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_table('cpd_activity_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('default_credits', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('imaging_protocols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('modality', sa.Enum('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'), nullable=True),
    sa.Column('body_part', sa.Enum('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('uses_contrast', sa.Boolean(), nullable=True),
    sa.Column('contrast_details', sa.Text(), nullable=True),
    sa.Column('technique_text', sa.Text(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imaging_protocols_body_part'), 'imaging_protocols', ['body_part'], unique=False)
    op.create_index(op.f('ix_imaging_protocols_modality'), 'imaging_protocols', ['modality'], unique=False)
    op.create_index(op.f('ix_imaging_protocols_name'), 'imaging_protocols', ['name'], unique=True)
    op.create_table('normal_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('body_part', sa.Enum('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'), nullable=True),
    sa.Column('modality', sa.Enum('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('reference_doi', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normal_measurements_body_part'), 'normal_measurements', ['body_part'], unique=False)
    op.create_index(op.f('ix_normal_measurements_modality'), 'normal_measurements', ['modality'], unique=False)
    op.create_index(op.f('ix_normal_measurements_name'), 'normal_measurements', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('recovery_phone', sa.String(length=20), nullable=True),
    sa.Column('recovery_email', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recovery_email'),
    sa.UniqueConstraint('recovery_phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('body_part', sa.Enum('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'), nullable=True),
    sa.Column('modality', sa.Enum('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('module', sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.Enum('STRUCTURED', 'CHECKLIST', 'NARRATIVE', name='template_type_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_report_templates_body_part'), 'admin_report_templates', ['body_part'], unique=False)
    op.create_index(op.f('ix_admin_report_templates_category'), 'admin_report_templates', ['category'], unique=False)
    op.create_index(op.f('ix_admin_report_templates_created_by_user_id'), 'admin_report_templates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_admin_report_templates_modality'), 'admin_report_templates', ['modality'], unique=False)
    op.create_index(op.f('ix_admin_report_templates_module'), 'admin_report_templates', ['module'], unique=False)
    op.create_index(op.f('ix_admin_report_templates_template_name'), 'admin_report_templates', ['template_name'], unique=True)
    op.create_index(op.f('ix_admin_report_templates_template_type'), 'admin_report_templates', ['template_type'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('GUIDELINES', 'CLASSIFICATIONS', 'DIFFERENTIAL_DIAGNOSIS', 'VETTING_TOOLS', 'ANATOMY', 'CURATED_CONTENTS', 'REPORT_CHECKER', 'RAD_CALCULATORS', 'TNM_STAGING', 'IMAGE_SEARCH', 'PHYSICS', 'GOVERNANCE_AUDITS', 'COURSES', 'RESEARCH_TOOLS', 'MUSIC', 'REPORT_TEMPLATE', name='category_name'), nullable=False),
    sa.Column('module', sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name'), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2083), nullable=True),
    sa.Column('embed_code', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_category'), 'references', ['category'], unique=False)
    op.create_index(op.f('ix_references_file'), 'references', ['file'], unique=False)
    op.create_index(op.f('ix_references_module'), 'references', ['module'], unique=False)
    op.create_table('user_content_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('modified_filepath', sa.String(length=255), nullable=True),
    sa.Column('annotations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_cpd_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('appraisal_cycle_start', sa.String(length=20), nullable=False),
    sa.Column('appraisal_cycle_end', sa.String(length=20), nullable=False),
    sa.Column('current_cpd_year_start', sa.String(length=20), nullable=False),
    sa.Column('current_cpd_year_end', sa.String(length=20), nullable=False),
    sa.Column('appraisal_cycle_start_date', sa.Date(), nullable=True),
    sa.Column('appraisal_cycle_end_date', sa.Date(), nullable=True),
    sa.Column('current_cpd_year_start_date', sa.Date(), nullable=True),
    sa.Column('current_cpd_year_end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.Enum('VIEWED', 'BOOKMARKED', 'RECOMMENDED', 'REGISTERED', 'LOGGED_IN', 'LOGGED_OUT', 'UPDATED_PROFILE_PIC', 'UPDATED_USERNAME', 'UPDATED_EMAIL', 'UPDATED_REPORT_TEMPLATES', 'UPDATED_CATEGORY_MODULE_PREFERENCES', 'UPDATED_CONTENTS', 'ADDED_FEEDBACK', 'STARTED_SESSION', 'ENDED_SESSION', name='interaction_types', native_enum=False), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('content_rating', sa.Integer(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('current_login', sa.DateTime(), nullable=True),
    sa.Column('session_start_time', sa.DateTime(), nullable=True),
    sa.Column('session_end_time', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('is_productivity_log', sa.Boolean(), nullable=True),
    sa.Column('session_type', sa.Enum('tele', 'onsite-private', 'onsite-government/NHS', name='session_type_enum'), nullable=True),
    sa.Column('modalities_handled', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('subspecialty_tags', sa.ARRAY(sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name')), nullable=True),
    sa.Column('num_cases_reported', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default='123e4567-e89b-12d3-a456-426614174000', nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('user_display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET DEFAULT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(length=255), nullable=True),
    sa.Column('preferred_categories', sa.Text(), nullable=True),
    sa.Column('preferred_modules', sa.Text(), nullable=True),
    sa.Column('preferred_subspecialties', sa.ARRAY(sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name')), nullable=True),
    sa.Column('preferred_workplaces', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body_part', sa.Enum('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'), nullable=True),
    sa.Column('modality', sa.Enum('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('GUIDELINES', 'CLASSIFICATIONS', 'DIFFERENTIAL_DIAGNOSIS', 'VETTING_TOOLS', 'ANATOMY', 'CURATED_CONTENTS', 'REPORT_CHECKER', 'RAD_CALCULATORS', 'TNM_STAGING', 'IMAGE_SEARCH', 'PHYSICS', 'GOVERNANCE_AUDITS', 'COURSES', 'RESEARCH_TOOLS', 'MUSIC', 'REPORT_TEMPLATE', name='category_name'), nullable=True),
    sa.Column('module', sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name'), nullable=True),
    sa.Column('template_text', sa.Text(), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_report_templates_body_part'), 'user_report_templates', ['body_part'], unique=False)
    op.create_index(op.f('ix_user_report_templates_category'), 'user_report_templates', ['category'], unique=False)
    op.create_index(op.f('ix_user_report_templates_is_public'), 'user_report_templates', ['is_public'], unique=False)
    op.create_index(op.f('ix_user_report_templates_modality'), 'user_report_templates', ['modality'], unique=False)
    op.create_index(op.f('ix_user_report_templates_module'), 'user_report_templates', ['module'], unique=False)
    op.create_index(op.f('ix_user_report_templates_template_name'), 'user_report_templates', ['template_name'], unique=True)
    op.create_index(op.f('ix_user_report_templates_user_id'), 'user_report_templates', ['user_id'], unique=False)
    op.create_table('cpd_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('cpd_year_start', sa.String(length=20), nullable=False),
    sa.Column('cpd_year_end', sa.String(length=20), nullable=False),
    sa.Column('appraisal_cycle_start', sa.String(length=20), nullable=False),
    sa.Column('appraisal_cycle_end', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('has_reflection', sa.Boolean(), nullable=True),
    sa.Column('cpd_points_guideline', sa.String(length=50), nullable=True),
    sa.Column('cpd_points_claimed', sa.Float(), nullable=True),
    sa.Column('external_links', sa.Text(), nullable=True),
    sa.Column('certificate_filenames', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cpd_state_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['cpd_activity_types.id'], ),
    sa.ForeignKeyConstraint(['cpd_state_id'], ['user_cpd_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('VIEW', 'CLICK', 'IMPRESSION', 'USE_TEMPLATE', 'OPEN_STAGING', 'OPEN_PROTOCOL', name='user_event_type_enum'), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('normal_measurement_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classification_systems.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['normal_measurement_id'], ['normal_measurements.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_id'], ['imaging_protocols.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['admin_report_templates.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_analytics_events_classification_id'), 'user_analytics_events', ['classification_id'], unique=False)
    op.create_index(op.f('ix_user_analytics_events_content_id'), 'user_analytics_events', ['content_id'], unique=False)
    op.create_index(op.f('ix_user_analytics_events_content_type'), 'user_analytics_events', ['content_type'], unique=False)
    op.create_index(op.f('ix_user_analytics_events_event_type'), 'user_analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_analytics_events_normal_measurement_id'), 'user_analytics_events', ['normal_measurement_id'], unique=False)
    op.create_index(op.f('ix_user_analytics_events_protocol_id'), 'user_analytics_events', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_user_analytics_events_template_id'), 'user_analytics_events', ['template_id'], unique=False)
    op.create_index(op.f('ix_user_analytics_events_user_id'), 'user_analytics_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_analytics_events_user_id'), table_name='user_analytics_events')
    op.drop_index(op.f('ix_user_analytics_events_template_id'), table_name='user_analytics_events')
    op.drop_index(op.f('ix_user_analytics_events_protocol_id'), table_name='user_analytics_events')
    op.drop_index(op.f('ix_user_analytics_events_normal_measurement_id'), table_name='user_analytics_events')
    op.drop_index(op.f('ix_user_analytics_events_event_type'), table_name='user_analytics_events')
    op.drop_index(op.f('ix_user_analytics_events_content_type'), table_name='user_analytics_events')
    op.drop_index(op.f('ix_user_analytics_events_content_id'), table_name='user_analytics_events')
    op.drop_index(op.f('ix_user_analytics_events_classification_id'), table_name='user_analytics_events')
    op.drop_table('user_analytics_events')
    op.drop_table('cpd_logs')
    op.drop_index(op.f('ix_user_report_templates_user_id'), table_name='user_report_templates')
    op.drop_index(op.f('ix_user_report_templates_template_name'), table_name='user_report_templates')
    op.drop_index(op.f('ix_user_report_templates_module'), table_name='user_report_templates')
    op.drop_index(op.f('ix_user_report_templates_modality'), table_name='user_report_templates')
    op.drop_index(op.f('ix_user_report_templates_is_public'), table_name='user_report_templates')
    op.drop_index(op.f('ix_user_report_templates_category'), table_name='user_report_templates')
    op.drop_index(op.f('ix_user_report_templates_body_part'), table_name='user_report_templates')
    op.drop_table('user_report_templates')
    op.drop_table('user_profiles')
    op.drop_table('user_feedbacks')
    op.drop_table('user_data')
    op.drop_table('user_cpd_states')
    op.drop_table('user_content_states')
    op.drop_index(op.f('ix_references_module'), table_name='references')
    op.drop_index(op.f('ix_references_file'), table_name='references')
    op.drop_index(op.f('ix_references_category'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_admin_report_templates_template_type'), table_name='admin_report_templates')
    op.drop_index(op.f('ix_admin_report_templates_template_name'), table_name='admin_report_templates')
    op.drop_index(op.f('ix_admin_report_templates_module'), table_name='admin_report_templates')
    op.drop_index(op.f('ix_admin_report_templates_modality'), table_name='admin_report_templates')
    op.drop_index(op.f('ix_admin_report_templates_created_by_user_id'), table_name='admin_report_templates')
    op.drop_index(op.f('ix_admin_report_templates_category'), table_name='admin_report_templates')
    op.drop_index(op.f('ix_admin_report_templates_body_part'), table_name='admin_report_templates')
    op.drop_table('admin_report_templates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_normal_measurements_name'), table_name='normal_measurements')
    op.drop_index(op.f('ix_normal_measurements_modality'), table_name='normal_measurements')
    op.drop_index(op.f('ix_normal_measurements_body_part'), table_name='normal_measurements')
    op.drop_table('normal_measurements')
    op.drop_index(op.f('ix_imaging_protocols_name'), table_name='imaging_protocols')
    op.drop_index(op.f('ix_imaging_protocols_modality'), table_name='imaging_protocols')
    op.drop_index(op.f('ix_imaging_protocols_body_part'), table_name='imaging_protocols')
    op.drop_table('imaging_protocols')
    op.drop_table('cpd_activity_types')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_module'), table_name='contents')
    op.drop_index(op.f('ix_contents_keywords'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_filepath'), table_name='contents')
    op.drop_index(op.f('ix_contents_file'), table_name='contents')
    op.drop_index(op.f('ix_contents_content_tags'), table_name='contents')
    op.drop_index(op.f('ix_contents_category'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_classification_systems_short_code'), table_name='classification_systems')
    op.drop_index(op.f('ix_classification_systems_name'), table_name='classification_systems')
    op.drop_index(op.f('ix_classification_systems_modality'), table_name='classification_systems')
    op.drop_index(op.f('ix_classification_systems_category'), table_name='classification_systems')
    op.drop_index(op.f('ix_classification_systems_body_part'), table_name='classification_systems')
    op.drop_table('classification_systems')
    # ### end Alembic commands ###
