"""Add UserCPDState model

Revision ID: 22ea69421ee9
Revises: 15bd403890b9
Create Date: 2025-06-20 00:59:36.635918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ea69421ee9'
down_revision: Union[str, None] = '15bd403890b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cpd_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('appraisal_cycle_start', sa.String(length=10), nullable=False),
    sa.Column('appraisal_cycle_end', sa.String(length=10), nullable=False),
    sa.Column('current_cpd_year_start', sa.String(length=10), nullable=False),
    sa.Column('current_cpd_year_end', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cpd_states')
    # ### end Alembic commands ###
