"""added totp_secret column in User table

Revision ID: 28beceef35ab
Revises: 2d0489853060
Create Date: 2024-09-29 02:02:28.347319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28beceef35ab'
down_revision: Union[str, None] = '2d0489853060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
