"""user_report_instance created in models.py

Revision ID: 302c5c563ba3
Revises: 6ca3c6e6c628
Create Date: 2025-11-28 19:28:05.335192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302c5c563ba3'
down_revision: Union[str, None] = '6ca3c6e6c628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    # Indexes for module column on existing content tables
    op.create_index(
        op.f('ix_classification_systems_module'),
        'classification_systems',
        ['module'],
        unique=False,
    )
    op.create_index(
        op.f('ix_imaging_protocols_module'),
        'imaging_protocols',
        ['module'],
        unique=False,
    )
    op.create_index(
        op.f('ix_normal_measurements_module'),
        'normal_measurements',
        ['module'],
        unique=False,
    )

    # UserReportInstance table: per-case report outputs based on templates
    op.create_table(
        'user_report_instances',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            'user_id',
            sa.UUID(as_uuid=True),
            sa.ForeignKey('users.id', ondelete='CASCADE', onupdate='CASCADE'),
            nullable=False,
        ),
        sa.Column(
            'admin_template_id',
            sa.Integer(),
            sa.ForeignKey('admin_report_templates.id', ondelete='SET NULL', onupdate='CASCADE'),
            nullable=True,
        ),
        sa.Column(
            'user_template_id',
            sa.Integer(),
            sa.ForeignKey('user_report_templates.id', ondelete='SET NULL', onupdate='CASCADE'),
            nullable=True,
        ),
        # Structural anchors
        sa.Column(
            'modality',
            sa.Enum('CT', 'MRI', 'ULTRASOUND', 'X_RAY', 'PET_CT', 'OTHER', name='modality_enum'),
            nullable=True,
        ),
        sa.Column(
            'body_part',
            sa.Enum(
                'NEURO',
                'HEAD_AND_NECK',
                'MSK',
                'LUNG',
                'CARDIAC',
                'HEPATOBILIARY',
                'UROLOGY',
                'GYNAECOLOGY',
                'UPPER_GI',
                'VASCULAR',
                'BREAST',
                'SPINE',
                'UPPER_LIMB',
                'LOWER_LIMB',
                'ABDOMEN',
                'LOWER_GI',
                name='body_part_enum',
            ),
            nullable=True,
        ),
        sa.Column(
            'module',
            sa.Enum(
                'CASE_WORKSPACE',
                'PROTOCOLS',
                'NORMAL_MEASUREMENTS',
                'CHECKLISTS',
                'CLASSIFICATIONS',
                'ENDOCRINE',
                name='module_name',
            ),
            nullable=True,
        ),
        # Case context
        sa.Column('indication', sa.Text(), nullable=True),
        sa.Column('core_question', sa.Text(), nullable=True),
        sa.Column('case_identifier', sa.String(length=255), nullable=True),
        # Report payload
        sa.Column('report_text', sa.Text(), nullable=True),
        sa.Column('section_values_json', sa.JSON(), nullable=True),
        # Diagnosis and learning anchors (no direct patient identifiers)
        sa.Column('diagnosis', sa.String(length=255), nullable=True),
        sa.Column('diagnosis_details', sa.Text(), nullable=True),
        sa.Column('diagnosis_tags', sa.Text(), nullable=True),
        # Site / service context
        sa.Column('institution_name', sa.String(length=255), nullable=True),
        sa.Column('service_name', sa.String(length=255), nullable=True),
        # Lifecycle
        sa.Column(
            'status',
            sa.Enum('DRAFT', 'FINAL', 'AMENDED', name='report_status_enum'),
            nullable=False,
            server_default='DRAFT',
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('finalized_at', sa.DateTime(), nullable=True),
    )

    # Indexes for user_report_instances (for fast retrieval)
    op.create_index(
        'ix_user_report_instances_user_id',
        'user_report_instances',
        ['user_id'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_admin_template_id',
        'user_report_instances',
        ['admin_template_id'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_user_template_id',
        'user_report_instances',
        ['user_template_id'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_modality',
        'user_report_instances',
        ['modality'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_body_part',
        'user_report_instances',
        ['body_part'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_module',
        'user_report_instances',
        ['module'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_case_identifier',
        'user_report_instances',
        ['case_identifier'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_diagnosis',
        'user_report_instances',
        ['diagnosis'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_institution_name',
        'user_report_instances',
        ['institution_name'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_service_name',
        'user_report_instances',
        ['service_name'],
        unique=False,
    )
    op.create_index(
        'ix_user_report_instances_status',
        'user_report_instances',
        ['status'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    # Drop indexes and table for user_report_instances
    op.drop_index('ix_user_report_instances_status', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_service_name', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_institution_name', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_diagnosis', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_case_identifier', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_module', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_body_part', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_modality', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_user_template_id', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_admin_template_id', table_name='user_report_instances')
    op.drop_index('ix_user_report_instances_user_id', table_name='user_report_instances')
    op.drop_table('user_report_instances')

    # Drop module indexes on existing tables
    op.drop_index(op.f('ix_normal_measurements_module'), table_name='normal_measurements')
    op.drop_index(op.f('ix_imaging_protocols_module'), table_name='imaging_protocols')
    op.drop_index(op.f('ix_classification_systems_module'), table_name='classification_systems')
    # ### end Alembic commands ###
