"""add user_report_instances table

Revision ID: 38acfb339df0
Revises: 302c5c563ba3
Create Date: 2025-11-29 02:11:09.112003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '38acfb339df0'
down_revision: Union[str, None] = '302c5c563ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_report_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('admin_template_id', sa.Integer(), nullable=True),
    sa.Column('user_template_id', sa.Integer(), nullable=True),
    sa.Column('modality', postgresql.ENUM(name='modality_enum', create_type=False), nullable=True),
    sa.Column('body_part', postgresql.ENUM(name='body_part_enum', create_type=False), nullable=True),
    sa.Column('module', postgresql.ENUM(name='module_name', create_type=False), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('core_question', sa.Text(), nullable=True),
    sa.Column('case_identifier', sa.String(length=255), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('section_values_json', sa.JSON(), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('diagnosis_details', sa.Text(), nullable=True),
    sa.Column('diagnosis_tags', sa.Text(), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', 'AMENDED', name='report_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_template_id'], ['admin_report_templates.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_template_id'], ['user_report_templates.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_report_instances_admin_template_id'), 'user_report_instances', ['admin_template_id'], unique=False)
    op.create_index(op.f('ix_user_report_instances_body_part'), 'user_report_instances', ['body_part'], unique=False)
    op.create_index(op.f('ix_user_report_instances_case_identifier'), 'user_report_instances', ['case_identifier'], unique=False)
    op.create_index(op.f('ix_user_report_instances_diagnosis'), 'user_report_instances', ['diagnosis'], unique=False)
    op.create_index(op.f('ix_user_report_instances_institution_name'), 'user_report_instances', ['institution_name'], unique=False)
    op.create_index(op.f('ix_user_report_instances_modality'), 'user_report_instances', ['modality'], unique=False)
    op.create_index(op.f('ix_user_report_instances_module'), 'user_report_instances', ['module'], unique=False)
    op.create_index(op.f('ix_user_report_instances_service_name'), 'user_report_instances', ['service_name'], unique=False)
    op.create_index(op.f('ix_user_report_instances_status'), 'user_report_instances', ['status'], unique=False)
    op.create_index(op.f('ix_user_report_instances_user_id'), 'user_report_instances', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_report_instances_user_template_id'), 'user_report_instances', ['user_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_report_instances_user_template_id'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_user_id'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_status'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_service_name'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_module'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_modality'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_institution_name'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_diagnosis'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_case_identifier'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_body_part'), table_name='user_report_instances')
    op.drop_index(op.f('ix_user_report_instances_admin_template_id'), table_name='user_report_instances')
    op.drop_table('user_report_instances')
    # ### end Alembic commands ###
