"""add smart_helper_cards model

Revision ID: 4716e28da927
Revises: 38acfb339df0
Create Date: 2025-12-01 23:34:52.312748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4716e28da927'
down_revision: Union[str, None] = '38acfb339df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create new enums for smart helper section and kind.
    # These are new types and safe to create here.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'smart_helper_section_enum') THEN
                CREATE TYPE smart_helper_section_enum AS ENUM (
                    'ANY',
                    'INDICATION',
                    'COMPARISON',
                    'TECHNIQUE',
                    'OBSERVATIONS',
                    'CONCLUSION',
                    'RECOMMENDATIONS'
                );
            END IF;
        END
        $$;
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'smart_helper_kind_enum') THEN
                CREATE TYPE smart_helper_kind_enum AS ENUM (
                    'INFO',
                    'TECHNIQUE',
                    'MEASUREMENT',
                    'CLASSIFICATION',
                    'SCORE',
                    'DIFFERENTIAL',
                    'CHECKLIST',
                    'CONCLUSION_SENTENCE',
                    'RECOMMENDATION_SENTENCE',
                    'PITFALL',
                    'OTHER'
                );
            END IF;
        END
        $$;
        """
    )

    # Now create the smart_helper_cards table, reusing existing enum types
    # modality_enum, body_part_enum, and module_name directly by name.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS smart_helper_cards (
            id SERIAL PRIMARY KEY,
            section smart_helper_section_enum NOT NULL,
            kind smart_helper_kind_enum NOT NULL,
            token VARCHAR(255),
            modality modality_enum NULL,
            body_part body_part_enum NULL,
            module module_name NULL,
            min_age_years INTEGER,
            max_age_years INTEGER,
            sex VARCHAR(10),
            title VARCHAR(255) NOT NULL,
            summary TEXT,
            bullets_json JSON,
            insert_options_json JSON,
            definition_json JSON,
            tags TEXT,
            is_active BOOLEAN NOT NULL,
            priority INTEGER NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
        );
        """
    )

    # Create indexes using Alembic helpers (they don't affect enum types)
    op.create_index(op.f('ix_smart_helper_cards_body_part'), 'smart_helper_cards', ['body_part'], unique=False)
    op.create_index(op.f('ix_smart_helper_cards_is_active'), 'smart_helper_cards', ['is_active'], unique=False)
    op.create_index(op.f('ix_smart_helper_cards_kind'), 'smart_helper_cards', ['kind'], unique=False)
    op.create_index(op.f('ix_smart_helper_cards_modality'), 'smart_helper_cards', ['modality'], unique=False)
    op.create_index(op.f('ix_smart_helper_cards_module'), 'smart_helper_cards', ['module'], unique=False)
    op.create_index(op.f('ix_smart_helper_cards_section'), 'smart_helper_cards', ['section'], unique=False)
    op.create_index(op.f('ix_smart_helper_cards_token'), 'smart_helper_cards', ['token'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smart_helper_cards_token'), table_name='smart_helper_cards')
    op.drop_index(op.f('ix_smart_helper_cards_section'), table_name='smart_helper_cards')
    op.drop_index(op.f('ix_smart_helper_cards_module'), table_name='smart_helper_cards')
    op.drop_index(op.f('ix_smart_helper_cards_modality'), table_name='smart_helper_cards')
    op.drop_index(op.f('ix_smart_helper_cards_kind'), table_name='smart_helper_cards')
    op.drop_index(op.f('ix_smart_helper_cards_is_active'), table_name='smart_helper_cards')
    op.drop_index(op.f('ix_smart_helper_cards_body_part'), table_name='smart_helper_cards')
    op.drop_table('smart_helper_cards')
    # ### end Alembic commands ###
