"""imagin protool feature almost ready and cleaned secrets from git repo
'


Revision ID: 4e96f5706991
Revises: 171a3ea716d2
Create Date: 2025-11-18 17:40:01.051217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e96f5706991'
down_revision: Union[str, None] = '171a3ea716d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
