"""Add date fields to UserCPDState

Revision ID: 56022cc2e61b
Revises: 22ea69421ee9
Create Date: 2025-06-20 04:17:14.647621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56022cc2e61b'
down_revision: Union[str, None] = '22ea69421ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cpd_logs', 'cpd_year_start',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('cpd_logs', 'cpd_year_end',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('cpd_logs', 'appraisal_cycle_start',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('cpd_logs', 'appraisal_cycle_end',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('user_cpd_states', sa.Column('appraisal_cycle_start_date', sa.Date(), nullable=True))
    op.add_column('user_cpd_states', sa.Column('appraisal_cycle_end_date', sa.Date(), nullable=True))
    op.add_column('user_cpd_states', sa.Column('current_cpd_year_start_date', sa.Date(), nullable=True))
    op.add_column('user_cpd_states', sa.Column('current_cpd_year_end_date', sa.Date(), nullable=True))
    op.alter_column('user_cpd_states', 'appraisal_cycle_start',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('user_cpd_states', 'appraisal_cycle_end',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('user_cpd_states', 'current_cpd_year_start',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('user_cpd_states', 'current_cpd_year_end',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cpd_states', 'current_cpd_year_end',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('user_cpd_states', 'current_cpd_year_start',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('user_cpd_states', 'appraisal_cycle_end',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('user_cpd_states', 'appraisal_cycle_start',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('user_cpd_states', 'current_cpd_year_end_date')
    op.drop_column('user_cpd_states', 'current_cpd_year_start_date')
    op.drop_column('user_cpd_states', 'appraisal_cycle_end_date')
    op.drop_column('user_cpd_states', 'appraisal_cycle_start_date')
    op.alter_column('cpd_logs', 'appraisal_cycle_end',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('cpd_logs', 'appraisal_cycle_start',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('cpd_logs', 'cpd_year_end',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('cpd_logs', 'cpd_year_start',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
