"""Add user_template_id to analytics + bodypart updates

Revision ID: 5636a3dfc0cc
Revises: 4e96f5706991
Create Date: 2025-11-21 19:24:45.647633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5636a3dfc0cc'
down_revision: Union[str, None] = '4e96f5706991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics_events', sa.Column('user_template_id', sa.Integer(), nullable=True))
    op.create_index(
        op.f('ix_user_analytics_events_user_template_id'),
        'user_analytics_events',
        ['user_template_id'],
        unique=False,
    )
    op.create_foreign_key(
        None,
        'user_analytics_events',
        'user_report_templates',
        ['user_template_id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    # 🔹 Postgres ENUM update for BodyPartEnum
    # Add new values to existing enum type in Postgres
    op.execute("ALTER TYPE body_part_enum ADD VALUE IF NOT EXISTS 'ABDOMEN';")
    op.execute("ALTER TYPE body_part_enum ADD VALUE IF NOT EXISTS 'LOWER_GI';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_analytics_events', type_='foreignkey')
    op.drop_index(op.f('ix_user_analytics_events_user_template_id'), table_name='user_analytics_events')
    op.drop_column('user_analytics_events', 'user_template_id')
    # ### end Alembic commands ###