"""Updated User model to add recovery email and phone

Revision ID: 58afdc9eaf90
Revises: 4726a3538ac2
Create Date: 2024-09-28 17:29:20.081738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58afdc9eaf90'
down_revision: Union[str, None] = '4726a3538ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recover_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('recovery_email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['recovery_email'])
    op.create_unique_constraint(None, 'users', ['recover_phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'recovery_email')
    op.drop_column('users', 'recover_phone')
    # ### end Alembic commands ###
