"""add template_type and admin_template_id to user_report_templates

Revision ID: 5ba5dd3a8dae
Revises: 5636a3dfc0cc
Create Date: 2025-11-23 00:00:47.134919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba5dd3a8dae'
down_revision: Union[str, None] = '5636a3dfc0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure existing string category values are compatible with the CategoryNames enum
    op.execute(
        "UPDATE admin_report_templates "
        "SET category = 'REPORT_TEMPLATE' "
        "WHERE category = 'Reporting Template'"
    )
    op.alter_column(
        'admin_report_templates',
        'category',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            'GUIDELINES',
            'CLASSIFICATIONS',
            'DIFFERENTIAL_DIAGNOSIS',
            'VETTING_TOOLS',
            'ANATOMY',
            'CURATED_CONTENTS',
            'REPORT_CHECKER',
            'RAD_CALCULATORS',
            'TNM_STAGING',
            'IMAGE_SEARCH',
            'PHYSICS',
            'GOVERNANCE_AUDITS',
            'COURSES',
            'RESEARCH_TOOLS',
            'MUSIC',
            'REPORT_TEMPLATE',
            name='category_name',
        ),
        existing_nullable=True,
        postgresql_using="category::category_name",
    )
    op.add_column('user_report_templates', sa.Column('template_type', sa.Enum('STRUCTURED', 'CHECKLIST', 'NARRATIVE', name='template_type_enum'), nullable=True))
    op.add_column('user_report_templates', sa.Column('admin_template_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_report_templates_admin_template_id'), 'user_report_templates', ['admin_template_id'], unique=False)
    op.create_index(op.f('ix_user_report_templates_template_type'), 'user_report_templates', ['template_type'], unique=False)
    op.create_foreign_key(None, 'user_report_templates', 'admin_report_templates', ['admin_template_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_report_templates', type_='foreignkey')
    op.drop_index(op.f('ix_user_report_templates_template_type'), table_name='user_report_templates')
    op.drop_index(op.f('ix_user_report_templates_admin_template_id'), table_name='user_report_templates')
    op.drop_column('user_report_templates', 'admin_template_id')
    op.drop_column('user_report_templates', 'template_type')
    op.alter_column('admin_report_templates', 'category',
               existing_type=sa.Enum('GUIDELINES', 'CLASSIFICATIONS', 'DIFFERENTIAL_DIAGNOSIS', 'VETTING_TOOLS', 'ANATOMY', 'CURATED_CONTENTS', 'REPORT_CHECKER', 'RAD_CALCULATORS', 'TNM_STAGING', 'IMAGE_SEARCH', 'PHYSICS', 'GOVERNANCE_AUDITS', 'COURSES', 'RESEARCH_TOOLS', 'MUSIC', 'REPORT_TEMPLATE', name='category_name'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
