""" Add loast_login column in UserData model.Delete interaction_date column. 

Revision ID: 6777b679ef70
Revises: cce4286ac94a
Create Date: 2024-09-16 01:33:04.518046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6777b679ef70'
down_revision = 'cce4286ac94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('last_interaction',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('interaction_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interaction_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('last_interaction',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
