"""Add external_links to CPDLog

Revision ID: 6fb26fad3b7e
Revises: f2e4d945ae17
Create Date: 2025-06-23 04:20:13.424389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb26fad3b7e'
down_revision: Union[str, None] = 'f2e4d945ae17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpd_logs', sa.Column('external_links', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpd_logs', 'external_links')
    # ### end Alembic commands ###
