"""add file row to contetns model

Revision ID: 86bcd39e26e6
Revises: 9d3bc2818d5d
Create Date: 2024-09-01 20:53:53.347722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bcd39e26e6'
down_revision = '9d3bc2818d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('embed_code', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guideline')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_contents_file'), ['file'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_file'))
        batch_op.drop_column('file')

    op.create_table('guideline',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=256), nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('embed_code', sa.TEXT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guidelines')
    # ### end Alembic commands ###
