"""Fix CPDLog ↔ UserCPDState relationship

Revision ID: 9be99f83469a
Revises: 85714800c9bb
Create Date: 2025-06-22 01:57:10.091874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be99f83469a'
down_revision: Union[str, None] = '85714800c9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cpdlog_cpdstate', 'cpd_logs', type_='foreignkey')
    op.create_foreign_key(None, 'cpd_logs', 'user_cpd_states', ['cpd_state_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cpd_logs', type_='foreignkey')
    op.create_foreign_key('fk_cpdlog_cpdstate', 'cpd_logs', 'user_cpd_states', ['cpd_state_id'], ['id'])
    # ### end Alembic commands ###
