"""empty message

Revision ID: 9d3bc2818d5d
Revises: 00f15f92ecc4
Create Date: 2024-08-31 15:21:54.222992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '9d3bc2818d5d'
down_revision = '00f15f92ecc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # Remove server defaults if they are not needed post-migration
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email', server_default=None)
        batch_op.alter_column('status', server_default=None)
        batch_op.alter_column('created_at', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('email')

    # ### end Alembic commands ###