"""Recreate initial migration after resolving revision issue

Revision ID: 9e15c25e82cf
Revises: fad9e2ade224
Create Date: 2024-09-09 23:23:28.476852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e15c25e82cf'
down_revision = 'fad9e2ade224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body_part', sa.Enum('NEURO', 'HEAD_AND_NECK', 'ENT', 'PEDIATRICS', 'MSK', 'LUNG', 'CARDIAC', 'ENDOCRINE', 'HEPATOBILIARY', 'UROLOGY', 'GYNAECOLOGY', 'UPPER_GI', 'VASCULAR', 'ONCOLOGY', 'MISCELLANEOUS', 'BREAST', 'OTHERS', name='body_part_enum'), nullable=False),
    sa.Column('modality', sa.Enum('CT', 'X_RAY', 'MRI', 'ULTRASOUND', 'NUCLEAR_MEDICINE', 'MAMMOGRAPHY', 'OTHERS', name='modality_enum'), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('GUIDELINES', 'CLASSIFICATIONS', 'DIFFERENTIAL_DIAGNOSIS', 'VETTING_TOOLS', 'ANATOMY', 'CURATED_CONTENTS', 'REPORT_CHECKER', 'RAD_CALCULATORS', 'TNM_STAGING', 'IMAGE_SEARCH', 'PHYSICS', 'GOVERNANCE_AUDITS', 'COURSES', 'RESEARCH_TOOLS', 'MUSIC', 'REPORT_TEMPLATE', name='category_name'), nullable=True),
    sa.Column('module', sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name'), nullable=True),
    sa.Column('template_text', sa.Text(), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_report_templates_body_part'), ['body_part'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_modality'), ['modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_template_name'), ['template_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_report_templates_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_report_templates_body_part')
        batch_op.drop_index('ix_report_templates_category')
        batch_op.drop_index('ix_report_templates_is_public')
        batch_op.drop_index('ix_report_templates_modality')
        batch_op.drop_index('ix_report_templates_module')
        batch_op.drop_index('ix_report_templates_template_name')
        batch_op.drop_index('ix_report_templates_user_id')

    op.drop_table('report_templates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body_part', sa.VARCHAR(length=13), nullable=False),
    sa.Column('modality', sa.VARCHAR(length=16), nullable=False),
    sa.Column('template_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=22), nullable=True),
    sa.Column('module', sa.VARCHAR(length=16), nullable=True),
    sa.Column('template_text', sa.TEXT(), nullable=True),
    sa.Column('file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index('ix_report_templates_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_report_templates_template_name', ['template_name'], unique=1)
        batch_op.create_index('ix_report_templates_module', ['module'], unique=False)
        batch_op.create_index('ix_report_templates_modality', ['modality'], unique=False)
        batch_op.create_index('ix_report_templates_is_public', ['is_public'], unique=False)
        batch_op.create_index('ix_report_templates_category', ['category'], unique=False)
        batch_op.create_index('ix_report_templates_body_part', ['body_part'], unique=False)

    with op.batch_alter_table('user_report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_report_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_template_name'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_module'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_modality'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_is_public'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_category'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_body_part'))

    op.drop_table('user_report_templates')
    # ### end Alembic commands ###
