"""Allow multiple appraisal cycles per user

Revision ID: 9e4719c3e6d7
Revises: 56022cc2e61b
Create Date: 2025-06-20 19:03:37.607712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4719c3e6d7'
down_revision: Union[str, None] = '56022cc2e61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_cpd_states_user_id_key', 'user_cpd_states', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_cpd_states_user_id_key', 'user_cpd_states', ['user_id'])
    # ### end Alembic commands ###
