"""Corrected column name from recover_pphone to recovery_phone

Revision ID: acb796f18656
Revises: 58afdc9eaf90
Create Date: 2024-09-28 22:49:23.536387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb796f18656'
down_revision: Union[str, None] = '58afdc9eaf90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recovery_phone', sa.String(length=20), nullable=True))
    op.drop_constraint('users_recover_phone_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['recovery_phone'])
    op.drop_column('users', 'recover_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recover_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_recover_phone_key', 'users', ['recover_phone'])
    op.drop_column('users', 'recovery_phone')
    # ### end Alembic commands ###
