"""add definition_json to user_report_templates

Revision ID: ae67332ad007
Revises: 13db3fc07d75
Create Date: 2025-11-24 16:41:13.895104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae67332ad007'
down_revision: Union[str, None] = '13db3fc07d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_report_templates', sa.Column('definition_json', sa.JSON(), nullable=True))
    op.alter_column('user_report_templates', 'template_type',
               existing_type=postgresql.ENUM('STRUCTURED', 'CHECKLIST', 'NARRATIVE', name='template_type_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_report_templates', 'template_type',
               existing_type=postgresql.ENUM('STRUCTURED', 'CHECKLIST', 'NARRATIVE', name='template_type_enum'),
               nullable=True)
    op.drop_column('user_report_templates', 'definition_json')
    # ### end Alembic commands ###
