"""empty message

Revision ID: b30e33aff5a6
Revises: 86bcd39e26e6
Create Date: 2024-09-02 19:58:14.114099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30e33aff5a6'
down_revision = '86bcd39e26e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(length=255), nullable=True))
        batch_op.drop_index('ix_contents_file')
        batch_op.create_index(batch_op.f('ix_contents_filepath'), ['filepath'], unique=False)
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_contents_filepath'))
        batch_op.create_index('ix_contents_file', ['file'], unique=False)
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###
