"""add module to protocols/measurements and module+tags to classifications

Revision ID: b33312169f20
Revises: ae67332ad007
Create Date: 2025-11-27 00:54:56.752144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33312169f20'
down_revision: Union[str, None] = 'ae67332ad007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###

    # 1) Extend the existing body_part_enum with new values used in the Python BodyPartEnum.
    # We only add new values here; removal of old values is not strictly required and is
    # more complex/unsafe in production.
    op.execute("ALTER TYPE body_part_enum ADD VALUE IF NOT EXISTS 'SPINE'")
    op.execute("ALTER TYPE body_part_enum ADD VALUE IF NOT EXISTS 'UPPER_LIMB'")
    op.execute("ALTER TYPE body_part_enum ADD VALUE IF NOT EXISTS 'LOWER_LIMB'")

    # 2) Add module columns using the existing module_name enum type.
    # We use raw SQL here to bind to the already-defined enum type module_name.
    op.execute("ALTER TABLE imaging_protocols ADD COLUMN IF NOT EXISTS module module_name")
    op.execute("ALTER TABLE normal_measurements ADD COLUMN IF NOT EXISTS module module_name")
    op.execute("ALTER TABLE classification_systems ADD COLUMN IF NOT EXISTS module module_name")

    # 3) Add tags column to classification_systems for smarter search/filtering.
    op.add_column(
        "classification_systems",
        sa.Column("tags", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###

    # 1) Drop tags column from classification_systems.
    op.drop_column("classification_systems", "tags")

    # 2) Drop module columns from the three core tables.
    # We intentionally do NOT attempt to remove enum values from body_part_enum for safety.
    op.execute("ALTER TABLE classification_systems DROP COLUMN IF EXISTS module")
    op.execute("ALTER TABLE normal_measurements DROP COLUMN IF EXISTS module")
    op.execute("ALTER TABLE imaging_protocols DROP COLUMN IF EXISTS module")

    # Note: body_part_enum will retain the added values (SPINE, UPPER_LIMB, LOWER_LIMB)
    # even on downgrade; removing enum values in PostgreSQL is non-trivial and is
    # typically not necessary for application correctness.
    # ### end Alembic commands ###
