"""fixing cssacding

Revision ID: cce4286ac94a
Revises: 6b1518eed307
Create Date: 2024-09-15 17:45:22.399580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce4286ac94a'
down_revision = '6b1518eed307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_content_states', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_feedbacks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('user_report_templates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('template_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_body_part'), ['body_part'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_modality'), ['modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_templates_template_name'), ['template_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_report_templates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_report_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_template_name'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_module'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_modality'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_is_public'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_category'))
        batch_op.drop_index(batch_op.f('ix_user_report_templates_body_part'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('template_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_feedbacks', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_content_states', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
