"""Switch to multiple certificate filenames

Revision ID: f2e4d945ae17
Revises: 9be99f83469a
Create Date: 2025-06-23 03:38:45.806636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e4d945ae17'
down_revision: Union[str, None] = '9be99f83469a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpd_logs', sa.Column('certificate_filenames', sa.Text(), nullable=True))
    op.drop_column('cpd_logs', 'certificate_filepath')
    op.drop_column('cpd_logs', 'certificate_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpd_logs', sa.Column('certificate_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('cpd_logs', sa.Column('certificate_filepath', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('cpd_logs', 'certificate_filenames')
    # ### end Alembic commands ###
