"""UserContentStates model added

Revision ID: fad9e2ade224
Revises: fb8c7ea1bc1b
Create Date: 2024-09-08 20:32:41.118626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad9e2ade224'
down_revision = 'fb8c7ea1bc1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_content_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('modified_file_path', sa.String(length=255), nullable=True),
    sa.Column('annotations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guidelines')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidelines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=256), nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('embed_code', sa.TEXT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_content_states')
    # ### end Alembic commands ###
