"""sync enums with uppercase definitions

Revision ID: fcb60424b31f
Revises: dd2f2a6d0db6
Create Date: 2025-07-01 01:29:40.671997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcb60424b31f'
down_revision: Union[str, None] = 'dd2f2a6d0db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_data', 'modalities_handled',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('user_data', 'subspecialty_tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name')),
               existing_nullable=True)
    op.alter_column('user_profiles', 'preferred_subspecialties',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name')),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'preferred_subspecialties',
               existing_type=sa.ARRAY(sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name')),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('user_data', 'subspecialty_tags',
               existing_type=sa.ARRAY(sa.Enum('HEAD_AND_NECK', 'NEURORADIOLOGY', 'CHEST', 'CARDIOVASCULAR', 'BREAST', 'GASTROINTESTINAL', 'ABDOMINAL', 'GENITOURINARY', 'MUSCULOSKELETAL', 'VASCULAR', 'PEDIATRIC', 'ONCOLOGIC', 'EMERGENCY', 'INTERVENTIONAL', 'NUCLEAR_MEDICINE', 'RADIOGRAPHERS', 'OTHERS', name='module_name')),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('user_data', 'modalities_handled',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    # ### end Alembic commands ###
