graph TD;
    A["Any high-risk features?"] -->|Yes| B[Urgent HPB MDT discussion]
    A -->|No| C["Any worrisome features?"]
    C -->|Yes| D["EUS + aspiration +/- contrast"]
    D --> E["Rediscuss at HPB MDT"]
    E --> F[Surgery]
    C -->|No| G["Cyst growth or other worrisome features at 6/12?"]
    G -->|Yes| H["Enter surveillance"]
    G -->|No| I["MRI/CT in 6 months to assess stability"]
    I --> J["Surveillance intervals based on size"]
    J --> K[">3cm: Alternate EUS and MRI/CT every 6 months"]
    J --> L["2-3cm: MRI/CT yearly"]
    J --> M["1-2cm: MRI/CT in 2 years"]
    J --> N["<1cm: MRI/CT in 2 years"]